// <auto-generated />
using System;
using GerenciaPomar.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerenciaPomar.Repository.Migrations
{
    [DbContext(typeof(PomarContext))]
    [Migration("20200702041840_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GerenciaPomar.Core.Models.Arvore", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoEspecie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPlantio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GrupoArvoreCodigo")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoEspecie");

                    b.HasIndex("GrupoArvoreCodigo");

                    b.ToTable("Arvores");
                });

            modelBuilder.Entity("GerenciaPomar.Core.Models.Colheita", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoArvore")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoGrupoArvore")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataColheita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Informacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoBruto")
                        .HasColumnType("float");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoArvore");

                    b.HasIndex("CodigoGrupoArvore");

                    b.ToTable("Colheitas");
                });

            modelBuilder.Entity("GerenciaPomar.Core.Models.Especie", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("GerenciaPomar.Core.Models.GrupoArvore", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("GruposArvores");
                });

            modelBuilder.Entity("GerenciaPomar.Core.Models.Arvore", b =>
                {
                    b.HasOne("GerenciaPomar.Core.Models.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("CodigoEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciaPomar.Core.Models.GrupoArvore", null)
                        .WithMany("Arvores")
                        .HasForeignKey("GrupoArvoreCodigo");
                });

            modelBuilder.Entity("GerenciaPomar.Core.Models.Colheita", b =>
                {
                    b.HasOne("GerenciaPomar.Core.Models.Arvore", "Arvore")
                        .WithMany()
                        .HasForeignKey("CodigoArvore")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciaPomar.Core.Models.GrupoArvore", "GrupoArvore")
                        .WithMany()
                        .HasForeignKey("CodigoGrupoArvore")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
